export const crewIT: any[] = [
{
    "docs": [
        {
            "_id": "2018-12-17T13:17:55.923Z_10",
            "template": "Crew List_IT",
            "status": "Public",
            "data": {
                "record_information": {
                    "catalogue_id": "10",
                    "date_from": "2018-12-17",
                    "date_until": "2020-09-22T21:42:18",
                    "name": "Massimo",
                    "surname": "Ponasso",
                    "role_in_project": ""
                },
                "source_identity": {
                    "archive_library": "Archivio di Stato di Genova",
                    "archive_library_location": "Genova",
                    "register_number": "13",
                    "number_of_document": "4042",
                    "date_of_document": "1853-07-18",
                    "date_of_document_to": "",
                    "issuing_authority": "Direzione Marittima di Genova",
                    "issuing_authority_location": "Genova",
                    "source_type_name": "",
                    "fond_number": "",
                    "fond_title": "",
                    "fond_series_number": "",
                    "file_number": "",
                    "file_tile": "",
                    "note": "",
                    "comment": ""
                },
                "ship_records": {
                    "ship_name": "San Fortunato",
                    "ship_type": "Brigantino",
                    "ship_tonnage": "150,91",
                    "construction_location": "Prà",
                    "construction_location_date": "1842",
                    "ammunition_type": "",
                    "ammunition_quantity_value": "",
                    "ammunition_quantity_unit": "",
                    "registry_port": "Genova",
                    "registry_number": "1913",
                    "organization_name": "",
                    "owner_name": "Michele",
                    "owner_surname": "Bertolotto",
                    "owner_fathers_name": "",
                    "note": "",
                    "comment": ""
                },
                "ports_of_call": {
                    "date_from": "1853-07-18",
                    "date_to": "1854-03-28",
                    "total_duration_months": "07",
                    "total_duration_years": "05",
                    "first_planned_destinations": "",
                    "total_crew_number": "10",
                    "note": "",
                    "comment": ""
                },
                "crew_list": {
                    "0": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-07-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1854-03-28",
                        "crew_surname": "Marini",
                        "crew_name": "Michele",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1825",
                        "crew_serial_number": "2371",
                        "crew_profession_type": "Capitano di Seconda Classe",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "2",
                        "crew_profession_months": "7",
                        "crew_profession_days": "05",
                        "crew_profession_pension_funds": "25,08"
                    },
                    "1": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-07-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1853-11-08",
                        "crew_surname": "Oneto",
                        "crew_name": "Prospero",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1827",
                        "crew_serial_number": "133",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1",
                        "crew_profession_months": "3",
                        "crew_profession_days": "21",
                        "crew_profession_pension_funds": "4,07"
                    },
                    "2": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-07-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1853-11-08",
                        "crew_surname": "Olivari",
                        "crew_name": "Gio.Batta",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1802",
                        "crew_serial_number": "1503",
                        "crew_profession_type": "Dispensiere",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1,12",
                        "crew_profession_months": "3",
                        "crew_profession_days": "21",
                        "crew_profession_pension_funds": "4,07"
                    },
                    "3": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-07-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1853-11-08",
                        "crew_surname": "Oneto",
                        "crew_name": "Giovanni Germano",
                        "crew_birth_location": "Portofino",
                        "crew_birth_date": "1827",
                        "crew_serial_number": "3158",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1",
                        "crew_profession_months": "3",
                        "crew_profession_days": "21",
                        "crew_profession_pension_funds": "4,07"
                    },
                    "4": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-07-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1854-03-28",
                        "crew_surname": "Massa",
                        "crew_name": "Emanuele",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1822",
                        "crew_serial_number": "2318",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1",
                        "crew_profession_months": "7",
                        "crew_profession_days": "05",
                        "crew_profession_pension_funds": "7,88"
                    },
                    "5": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-07-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1853-11-08",
                        "crew_surname": "Olivari",
                        "crew_name": "Agostino",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1833",
                        "crew_serial_number": "8564",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1",
                        "crew_profession_months": "3",
                        "crew_profession_days": "14",
                        "crew_profession_pension_funds": "3,77",
                        "note": "Sbarcato a Genova l`8 Novembre 1853 causa ricovero in ospedale"
                    },
                    "6": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-07-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1854-03-28",
                        "crew_surname": "Gardella",
                        "crew_name": "Giovanni",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1835",
                        "crew_serial_number": "8075",
                        "crew_profession_type": "Mozzo",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "0,75",
                        "crew_profession_months": "7",
                        "crew_profession_days": "05",
                        "crew_profession_pension_funds": "7,88"
                    },
                    "7": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-07-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1853-11-08",
                        "crew_surname": "Olivari",
                        "crew_name": "Luigi",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1836",
                        "crew_serial_number": "10553",
                        "crew_profession_type": "Mozzo",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "0,75",
                        "crew_profession_months": "3",
                        "crew_profession_days": "21",
                        "crew_profession_pension_funds": "2,96"
                    },
                    "8": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-07-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1854-03-28",
                        "crew_surname": "Marini",
                        "crew_name": "Francesco",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1839",
                        "crew_serial_number": "10739",
                        "crew_profession_type": "Mozzo",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "0,33",
                        "crew_profession_months": "7",
                        "crew_profession_days": "0,5",
                        "crew_profession_pension_funds": "5,79"
                    },
                    "9": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-07-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1853-11-08",
                        "crew_surname": "Codignola",
                        "crew_name": "Giuseppe",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1819",
                        "crew_serial_number": "1501",
                        "crew_profession_type": "Secondo",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1,50",
                        "crew_profession_months": "3",
                        "crew_profession_days": "21",
                        "crew_profession_pension_funds": "5,55"
                    },
                    "10": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-12-15",
                        "discharge_port": "Genova",
                        "discharge_date": "1854-03-28",
                        "crew_surname": "Bertolotto",
                        "crew_name": "Giuseppe",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1814",
                        "crew_serial_number": "41221",
                        "crew_profession_type": "Secondo",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1,50",
                        "crew_profession_months": "3",
                        "crew_profession_days": "14",
                        "crew_profession_pension_funds": "5,20"
                    },
                    "11": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-12-15",
                        "discharge_port": "Genova",
                        "discharge_date": "1854-03-28",
                        "crew_surname": "Schiaffino",
                        "crew_name": "Giuseppe",
                        "crew_birth_location": "Portofino",
                        "crew_birth_date": "1821",
                        "crew_serial_number": "1193",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1",
                        "crew_profession_months": "3",
                        "crew_profession_days": "14",
                        "crew_profession_pension_funds": "3,81"
                    },
                    "12": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-12-15",
                        "discharge_port": "Genova",
                        "discharge_date": "1854-03-28",
                        "crew_surname": "Lavarello",
                        "crew_name": "Giuseppe",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1832",
                        "crew_serial_number": "1721",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1",
                        "crew_profession_months": "3",
                        "crew_profession_days": "14",
                        "crew_profession_pension_funds": "3,81"
                    },
                    "13": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-12-15",
                        "discharge_port": "Genova",
                        "discharge_date": "1854-03-28",
                        "crew_surname": "Valle",
                        "crew_name": "Giovanni",
                        "crew_birth_location": "Portofino",
                        "crew_birth_date": "1833",
                        "crew_serial_number": "4447",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1",
                        "crew_profession_months": "3",
                        "crew_profession_days": "14",
                        "crew_profession_pension_funds": "3,81"
                    },
                    "14": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1853-12-15",
                        "discharge_port": "Genova",
                        "discharge_date": "1854-03-28",
                        "crew_surname": "Mortola",
                        "crew_name": "Biagio",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1831",
                        "crew_serial_number": "7002",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1",
                        "crew_profession_months": "3",
                        "crew_profession_days": "14",
                        "crew_profession_pension_funds": "3,81"
                    }
                },
                "route": {
                    "0": {
                        "departure_port": "Costantinopoli",
                        "departure_date": "1853-08-28"
                    },
                    "1": {
                        "departure_port": "Kertch",
                        "departure_date": "1853-07-06"
                    },
                    "2": {
                        "departure_port": "Berdiansk",
                        "departure_date": "1853-09-16"
                    },
                    "3": {
                        "departure_port": "Costantinopoli",
                        "departure_date": "1853-10-04"
                    },
                    "4": {
                        "departure_port": "Genova",
                        "departure_date": "1853-12-15"
                    },
                    "5": {
                        "departure_port": "Talamone",
                        "departure_date": "1854-01-02"
                    },
                    "6": {
                        "departure_port": "Salonicco",
                        "departure_date": "1854-02-13"
                    },
                    "7": {},
                    "8": {},
                    "9": {},
                    "10": {},
                    "11": {},
                    "12": {},
                    "13": {},
                    "14": {}
                }
            }
        }
    ]
},
{
    "docs": [
        {
            "_id": "2018-03-20T13:21:30.542Z_4",
            "template": "Crew List_IT",
            "status": "Public",
            "data": {
                "record_information": {
                    "catalogue_id": "4",
                    "date_from": "2018-03-20",
                    "date_until": "2020-09-22T21:40:38",
                    "name": "Benedetta",
                    "surname": "Risso",
                    "role_in_project": ""
                },
                "source_identity": {
                    "archive_library": "Archivio di Stato di Genova",
                    "archive_library_location": "Genova",
                    "register_number": "3780",
                    "number_of_document": "14",
                    "date_of_document": "1859-06-06",
                    "date_of_document_to": "",
                    "issuing_authority": "Direzione Marittima di Genova",
                    "issuing_authority_location": "Genova",
                    "source_type_name": "",
                    "fond_number": "",
                    "fond_title": "",
                    "fond_series_number": "",
                    "file_number": "",
                    "file_tile": "",
                    "note": "",
                    "comment": ""
                },
                "ship_records": {
                    "ship_name": "Rosina",
                    "ship_type": "Brigantino",
                    "ship_tonnage": "136,85",
                    "construction_location": "Varazze",
                    "construction_location_date": "1850",
                    "ammunition_type": "",
                    "ammunition_quantity_value": "",
                    "ammunition_quantity_unit": "",
                    "registry_port": "Genova",
                    "registry_number": "1295",
                    "organization_name": "",
                    "owner_name": "Prospero",
                    "owner_surname": "Schiaffino",
                    "owner_fathers_name": "",
                    "note": "",
                    "comment": ""
                },
                "ports_of_call": {
                    "date_from": "1859-06-06",
                    "date_to": "1861-04-04",
                    "total_duration_months": "21",
                    "total_duration_years": "29",
                    "first_planned_destinations": "Mar Nero",
                    "total_crew_number": "9",
                    "note": "",
                    "comment": ""
                },
                "crew_list": {
                    "0": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1859-06-06",
                        "discharge_port": "Genova",
                        "discharge_date": "1861-04-04",
                        "crew_surname": "Ovivari",
                        "crew_name": "Fortunato",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1824",
                        "crew_serial_number": "6294",
                        "crew_profession_type": "Capitano di seconda classe",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "2",
                        "crew_profession_months": "21",
                        "crew_profession_days": "29",
                        "crew_profession_pension_funds": "76,88"
                    },
                    "1": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1859-06-06",
                        "discharge_port": "Genova",
                        "discharge_date": "1861-04-04",
                        "crew_surname": "Mortola",
                        "crew_name": "Antonio",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1833",
                        "crew_serial_number": "8286",
                        "crew_profession_type": "Nostromo",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1,5",
                        "crew_profession_months": "21",
                        "crew_profession_days": "29",
                        "crew_profession_pension_funds": "32,95"
                    },
                    "2": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1859-06-06",
                        "discharge_port": "Portofino",
                        "discharge_date": "1860-06-26",
                        "crew_surname": "Mortola",
                        "crew_name": "Gio Batta",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1840",
                        "crew_serial_number": "12433",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "0,75",
                        "crew_profession_months": "12",
                        "crew_profession_days": "21",
                        "crew_profession_pension_funds": "19,97"
                    },
                    "3": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1859-06-06",
                        "discharge_port": "Portofino",
                        "discharge_date": "1860-06-26",
                        "crew_surname": "Costa",
                        "crew_name": "Gio Batta Matteo",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1841",
                        "crew_serial_number": "11953",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "0,75",
                        "crew_profession_months": "12",
                        "crew_profession_days": "21",
                        "crew_profession_pension_funds": "19,97"
                    },
                    "4": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1859-06-06",
                        "discharge_port": "Portofino",
                        "discharge_date": "1860-06-26",
                        "crew_surname": "Castagneto",
                        "crew_name": "Franco Angelo",
                        "crew_birth_location": "Santa Margherita",
                        "crew_birth_date": "1840",
                        "crew_serial_number": "6682",
                        "crew_profession_type": "Mozzo",
                        "crew_profession_months": "12",
                        "crew_profession_days": "21",
                        "crew_profession_pension_funds": "19,97"
                    },
                    "5": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1859-06-06",
                        "discharge_port": "Portofino",
                        "discharge_date": "1860-06-26",
                        "crew_surname": "Olivari",
                        "crew_name": "Bartolomeo Luigi",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1842",
                        "crew_serial_number": "14212",
                        "crew_profession_type": "Mozzo",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "0,5",
                        "crew_profession_months": "12",
                        "crew_profession_days": "21",
                        "crew_profession_pension_funds": "19,97"
                    },
                    "6": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1859-06-06",
                        "discharge_port": "Marsiglia",
                        "discharge_date": "1861-02-12",
                        "crew_surname": "Mortola",
                        "crew_name": "Fortunato",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1848",
                        "crew_serial_number": "15732",
                        "crew_profession_type": "Mozzo",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "0,25",
                        "crew_profession_months": "21",
                        "crew_profession_days": "7",
                        "crew_profession_pension_funds": "16,99"
                    },
                    "7": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1859-06-06",
                        "discharge_port": "Marsiglia",
                        "discharge_date": "1860-06-04",
                        "crew_surname": "Balestra",
                        "crew_name": "Gio Batta",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1840",
                        "crew_serial_number": "11917",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1",
                        "crew_profession_months": "11",
                        "crew_profession_days": "29",
                        "crew_profession_pension_funds": "13,16"
                    },
                    "8": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1859-06-06",
                        "discharge_port": "Portofino",
                        "discharge_date": "1860-06-26",
                        "crew_surname": "Deandreis",
                        "crew_name": "Giovanni Battista",
                        "crew_birth_location": "Oneglia",
                        "crew_birth_date": "1843",
                        "crew_serial_number": "2476",
                        "crew_profession_type": "Mozzo",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "0,5",
                        "crew_profession_months": "12",
                        "crew_profession_days": "21",
                        "crew_profession_pension_funds": "10,16"
                    },
                    "9": {
                        "embarkation_port": "Portofino",
                        "embarkation_date": "1860-07-06",
                        "discharge_port": "Genova",
                        "discharge_date": "1861-04-04",
                        "crew_surname": "Guinelli",
                        "crew_name": "Antonio",
                        "crew_birth_location": "Portofino",
                        "crew_birth_date": "1843",
                        "crew_serial_number": "6897",
                        "crew_profession_type": "Mozzo",
                        "crew_profession_months": "8",
                        "crew_profession_days": "25",
                        "crew_profession_pension_funds": "7,07"
                    },
                    "10": {
                        "embarkation_port": "Portofino",
                        "embarkation_date": "1860-07-06",
                        "discharge_port": "Genova",
                        "discharge_date": "1861-04-04",
                        "crew_surname": "Schiaffino",
                        "crew_name": "Simone",
                        "crew_birth_location": "Portofino",
                        "crew_birth_date": "1843",
                        "crew_serial_number": "7087",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1",
                        "crew_profession_months": "8",
                        "crew_profession_days": "25",
                        "crew_profession_pension_funds": "7,07"
                    },
                    "11": {
                        "embarkation_port": "Portofino",
                        "embarkation_date": "1860-07-06",
                        "discharge_port": "Marsiglia",
                        "discharge_date": "1861-02-07",
                        "crew_surname": "Perazzo",
                        "crew_name": "Gio Batta",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1834",
                        "crew_serial_number": "15848",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1",
                        "crew_profession_months": "7",
                        "crew_profession_days": "2",
                        "crew_profession_pension_funds": "5,65"
                    },
                    "12": {
                        "embarkation_port": "Portofino",
                        "embarkation_date": "1860-07-06",
                        "discharge_port": "Genova",
                        "discharge_date": "1861-04-04",
                        "crew_surname": "Pellerena",
                        "crew_name": "Gio Batta",
                        "crew_birth_location": "San Lorenzo della Costa",
                        "crew_birth_date": "1842",
                        "crew_serial_number": "7000",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1",
                        "crew_profession_months": "8",
                        "crew_profession_days": "25",
                        "crew_profession_pension_funds": "9,72"
                    },
                    "13": {
                        "embarkation_port": "Portofino",
                        "embarkation_date": "1860-07-06",
                        "discharge_port": "Genova",
                        "discharge_date": "1861-04-04",
                        "crew_surname": "Galeazzo",
                        "crew_name": "Gio Batta",
                        "crew_birth_location": "San Giacomo di Corte",
                        "crew_birth_date": "1843",
                        "crew_serial_number": "6867",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "1",
                        "crew_profession_months": "8",
                        "crew_profession_days": "25",
                        "crew_profession_pension_funds": "7,07"
                    },
                    "14": {
                        "embarkation_port": "Portofino",
                        "embarkation_date": "1860-07-08",
                        "discharge_port": "Genova",
                        "discharge_date": "1861-04-04",
                        "crew_surname": "Cafferata",
                        "crew_name": "Giuseppe",
                        "crew_birth_location": "Sori",
                        "crew_birth_date": "1844",
                        "crew_serial_number": "14885",
                        "crew_profession_type": "Mozzo",
                        "crew_profession_wage": "Share",
                        "crew_profession_value": "0,6",
                        "crew_profession_months": "8",
                        "crew_profession_days": "23",
                        "crew_profession_pension_funds": "7,07"
                    },
                    "15": {
                        "embarkation_port": "Marsiglia",
                        "embarkation_date": "1861-03-05",
                        "discharge_port": "Genova",
                        "discharge_date": "1861-04-04",
                        "crew_surname": "Schiaffino",
                        "crew_name": "Giuseppe",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1849",
                        "crew_serial_number": "17165",
                        "crew_profession_type": "Mozzo",
                        "crew_profession_months": "1",
                        "crew_profession_pension_funds": "0,80"
                    }
                },
                "route": {
                    "0": {
                        "departure_port": "Costantinopoli",
                        "departure_date": "1859-08-25"
                    },
                    "1": {
                        "departure_port": "Kertch",
                        "departure_date": "1859-09-03"
                    },
                    "2": {
                        "departure_port": "Taganrog",
                        "departure_date": "1859-09-18"
                    },
                    "3": {
                        "departure_port": "Costantinopoli",
                        "departure_date": "1859-10-08"
                    },
                    "4": {
                        "departure_port": "Dardanelli",
                        "departure_date": "1859-10-25"
                    },
                    "5": {
                        "departure_port": "Costantinopoli",
                        "departure_date": "1859-11-04"
                    },
                    "6": {
                        "departure_port": "Malta",
                        "departure_date": "1860-02-02"
                    },
                    "7": {
                        "departure_port": "Costantinopoli",
                        "departure_date": "1860-03-29"
                    },
                    "8": {
                        "departure_port": "Marsiglia",
                        "departure_date": "1860-05-12",
                        "arrival_port": "Marsiglia",
                        "arrival_date": "1860-06-19"
                    },
                    "9": {
                        "departure_port": "Costantinopoli",
                        "departure_date": "1860-09-13"
                    },
                    "10": {},
                    "11": {},
                    "12": {},
                    "13": {},
                    "14": {}
                }
            }
        }
    ]
},
{
    "docs": [
        {
            "_id": "2018-04-03T14:57:35.212Z_27",
            "template": "Crew List_IT",
            "status": "Public",
            "data": {
                "record_information": {
                    "catalogue_id": "27",
                    "date_from": "2018-04-03",
                    "date_until": "2020-09-22T21:38:11",
                    "name": "Carolina",
                    "surname": "Gaggero ",
                    "role_in_project": ""
                },
                "source_identity": {
                    "archive_library": "Archivio di Stato di Genova",
                    "archive_library_location": "Genova",
                    "register_number": "14",
                    "number_of_document": "9577",
                    "date_of_document": "1862-02-18",
                    "date_of_document_to": "",
                    "issuing_authority": "Direzione marittima di Genova",
                    "issuing_authority_location": "Genova",
                    "source_type_name": "",
                    "fond_number": "",
                    "fond_title": "",
                    "fond_series_number": "",
                    "file_number": "",
                    "file_tile": "",
                    "note": "",
                    "comment": ""
                },
                "ship_records": {
                    "ship_name": "Giuseppe",
                    "ship_type": "Brigantino",
                    "ship_tonnage": "176,19",
                    "construction_location": "Savona",
                    "construction_location_date": "1850",
                    "ammunition_type": "",
                    "ammunition_quantity_value": "",
                    "ammunition_quantity_unit": "",
                    "registry_port": "Genova",
                    "registry_number": "1319",
                    "organization_name": "",
                    "owner_name": "Domenico",
                    "owner_surname": "Antola",
                    "owner_fathers_name": "",
                    "note": "",
                    "comment": ""
                },
                "ports_of_call": {
                    "date_from": "1862-02-16",
                    "date_to": "1863-06-03",
                    "total_duration_months": "14",
                    "total_duration_years": "24",
                    "first_planned_destinations": "Azov",
                    "total_crew_number": "9",
                    "note": "",
                    "comment": ""
                },
                "crew_list": {
                    "0": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1862-02-16",
                        "discharge_port": "Genova",
                        "discharge_date": "1863-06-03",
                        "crew_surname": "Antola",
                        "crew_name": "Andrea",
                        "crew_birth_location": "Genova",
                        "crew_birth_date": "1824",
                        "crew_serial_number": "1677",
                        "crew_profession_type": "Capitano di seconda classe",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_months": "14",
                        "crew_profession_days": "14",
                        "crew_profession_pension_funds": "50,63"
                    },
                    "1": {
                        "embarkation_port": "Livorno",
                        "embarkation_date": "1862-03-10",
                        "discharge_port": "Genova",
                        "discharge_date": "1862-06-14",
                        "crew_surname": "Scriola",
                        "crew_name": "Stefano",
                        "crew_birth_location": "Genova",
                        "crew_birth_date": "1829",
                        "crew_serial_number": "359",
                        "crew_profession_type": "Secondo",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "87",
                        "crew_profession_months": "3",
                        "crew_profession_days": "5",
                        "crew_profession_pension_funds": "4,75"
                    },
                    "2": {
                        "embarkation_port": "Livorno",
                        "embarkation_date": "1862-03-10",
                        "discharge_port": "Marsiglia",
                        "discharge_date": "1862-11-20",
                        "crew_surname": "Canegra",
                        "crew_name": "Antonio Felice",
                        "crew_birth_location": "Sori",
                        "crew_birth_date": "1819",
                        "crew_serial_number": "3651",
                        "crew_profession_type": "Nostromo",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "77",
                        "crew_profession_months": "7",
                        "crew_profession_days": "19",
                        "crew_profession_pension_funds": "11,45"
                    },
                    "3": {
                        "embarkation_port": "Livorno",
                        "embarkation_date": "1862-03-10",
                        "discharge_port": "Genova",
                        "discharge_date": "1862-06-14",
                        "crew_surname": "Stagno",
                        "crew_name": "Antonio",
                        "crew_birth_location": "Sori",
                        "crew_birth_date": "1810",
                        "crew_serial_number": "2759",
                        "crew_profession_type": "Dispensiere",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "70",
                        "crew_profession_months": "3",
                        "crew_profession_days": "5",
                        "crew_profession_pension_funds": "3,48"
                    },
                    "4": {
                        "embarkation_port": "Livorno",
                        "embarkation_date": "1862-03-10",
                        "discharge_port": "Marsiglia",
                        "discharge_date": "1862-10-28",
                        "crew_surname": "Bozzo",
                        "crew_name": "Giacomo",
                        "crew_birth_location": "Camogli",
                        "crew_birth_date": "1843",
                        "crew_serial_number": "11447",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "60",
                        "crew_profession_months": "6",
                        "crew_profession_days": "27",
                        "crew_profession_pension_funds": "7,59"
                    },
                    "5": {
                        "embarkation_port": "Livorno",
                        "embarkation_date": "1862-03-10",
                        "discharge_port": "Genova",
                        "discharge_date": "1862-06-14",
                        "crew_surname": "Figari",
                        "crew_name": "Girolamo",
                        "crew_birth_location": "Sori",
                        "crew_birth_date": "1844",
                        "crew_serial_number": "15493",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "60",
                        "crew_profession_months": "3",
                        "crew_profession_days": "5",
                        "crew_profession_pension_funds": "3,48"
                    },
                    "6": {
                        "embarkation_port": "Livorno",
                        "embarkation_date": "1862-03-10",
                        "discharge_port": "Genova",
                        "discharge_date": "1862-06-14",
                        "crew_surname": "Valle",
                        "crew_name": "Antonio Felice",
                        "crew_birth_location": "Sori",
                        "crew_birth_date": "1842",
                        "crew_serial_number": "15416",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "60",
                        "crew_profession_months": "3",
                        "crew_profession_days": "5",
                        "crew_profession_pension_funds": "3,48"
                    },
                    "7": {
                        "embarkation_port": "Livorno",
                        "embarkation_date": "1862-03-10",
                        "discharge_port": "Genova",
                        "discharge_date": "1862-06-14",
                        "crew_surname": "Cavassa",
                        "crew_name": "Vincenzo",
                        "crew_birth_location": "Sori",
                        "crew_birth_date": "1845",
                        "crew_serial_number": "14201",
                        "crew_profession_type": "Giovinetto",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "47",
                        "crew_profession_months": "3",
                        "crew_profession_days": "5",
                        "crew_profession_pension_funds": "3,48"
                    },
                    "8": {
                        "embarkation_port": "Livorno",
                        "embarkation_date": "1862-03-10",
                        "discharge_port": "Genova",
                        "discharge_date": "1863-06-03",
                        "crew_surname": "Valle",
                        "crew_name": "Giuseppe",
                        "crew_birth_location": "Sori",
                        "crew_birth_date": "1847",
                        "crew_serial_number": "16785",
                        "crew_profession_type": "Mozzo",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "40",
                        "crew_profession_months": "14",
                        "crew_profession_days": "4",
                        "crew_profession_pension_funds": "11,25"
                    },
                    "9": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1862-07-07",
                        "discharge_port": "Genova",
                        "discharge_date": "1863-06-03",
                        "crew_surname": "Antola",
                        "crew_name": "Giuseppe",
                        "crew_birth_location": "Genova",
                        "crew_birth_date": "1836",
                        "crew_serial_number": "8621",
                        "crew_profession_type": "Secondo",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "90",
                        "crew_profession_months": "10",
                        "crew_profession_days": "29",
                        "crew_profession_pension_funds": "16,35"
                    },
                    "10": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1862-07-07",
                        "discharge_port": "Marsiglia",
                        "discharge_date": "1862-10-25",
                        "crew_surname": "Forno",
                        "crew_name": "Andrea",
                        "crew_birth_location": "Genova",
                        "crew_birth_date": "1842",
                        "crew_serial_number": "12333",
                        "crew_profession_type": "Dispensiere",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "65",
                        "crew_profession_months": "3",
                        "crew_profession_days": "19",
                        "crew_profession_pension_funds": "4"
                    },
                    "11": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1862-07-07",
                        "discharge_port": "Marsiglia",
                        "discharge_date": "1862-10-25",
                        "crew_surname": "Dodero",
                        "crew_name": "Giobatta",
                        "crew_birth_location": "Genova",
                        "crew_birth_date": "1822",
                        "crew_serial_number": "5070",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "56",
                        "crew_profession_months": "3",
                        "crew_profession_days": "19",
                        "crew_profession_pension_funds": "4"
                    },
                    "12": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1862-07-07",
                        "discharge_port": "Marsiglia",
                        "discharge_date": "1862-10-25",
                        "crew_surname": "Ferrando",
                        "crew_name": "Nicolò",
                        "crew_birth_location": "Savona",
                        "crew_birth_date": "1843",
                        "crew_serial_number": "4897",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "56",
                        "crew_profession_months": "3",
                        "crew_profession_days": "19",
                        "crew_profession_pension_funds": "4"
                    },
                    "13": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1862-07-07",
                        "discharge_port": "Marsiglia",
                        "discharge_date": "1862-10-25",
                        "crew_surname": "Furigo",
                        "crew_name": "Francesco Domenico",
                        "crew_birth_location": "Savona",
                        "crew_birth_date": "1841",
                        "crew_serial_number": "4685",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "56",
                        "crew_profession_months": "3",
                        "crew_profession_days": "19",
                        "crew_profession_pension_funds": "4"
                    },
                    "14": {
                        "embarkation_port": "Genova",
                        "embarkation_date": "1862-07-07",
                        "discharge_port": "Genova",
                        "discharge_date": "1863-06-03",
                        "crew_surname": "Capurro",
                        "crew_name": "Paolo",
                        "crew_birth_location": "Genova",
                        "crew_birth_date": "1848",
                        "crew_serial_number": "15711",
                        "crew_profession_type": "Mozzo",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "20",
                        "crew_profession_months": "10",
                        "crew_profession_days": "27",
                        "crew_profession_pension_funds": "8,27"
                    },
                    "15": {
                        "embarkation_port": "Marsiglia",
                        "embarkation_date": "1863-02-18",
                        "discharge_port": "Marsiglia",
                        "discharge_date": "1863-02-18",
                        "crew_surname": "Antola",
                        "crew_name": "Giuseppe",
                        "crew_birth_location": "Sori",
                        "crew_birth_date": "1836",
                        "crew_serial_number": "862",
                        "crew_profession_type": "Secondo",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "96",
                        "note": "sceso all`imbarco"
                    },
                    "16": {
                        "embarkation_port": "Marsiglia",
                        "embarkation_date": "1863-02-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1863-06-03",
                        "crew_surname": "Canessa",
                        "crew_name": "Antonio Felice",
                        "crew_birth_location": "Sori",
                        "crew_birth_date": "1819",
                        "crew_serial_number": "3651",
                        "crew_profession_type": "Nostromo",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "77",
                        "crew_profession_months": "3",
                        "crew_profession_days": "16",
                        "crew_profession_pension_funds": "5,30"
                    },
                    "17": {
                        "embarkation_port": "Marsiglia",
                        "embarkation_date": "1863-02-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1863-06-03",
                        "crew_surname": "Fontana",
                        "crew_name": "Francesco",
                        "crew_birth_location": "Sori",
                        "crew_birth_date": "1842",
                        "crew_serial_number": "11821",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "60",
                        "crew_profession_months": "3",
                        "crew_profession_days": "16",
                        "crew_profession_pension_funds": "3,89"
                    },
                    "18": {
                        "embarkation_port": "Marsiglia",
                        "embarkation_date": "1863-02-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1863-06-03",
                        "crew_surname": "Vallebona",
                        "crew_name": "Giuseppe",
                        "crew_birth_location": "Sori",
                        "crew_birth_date": "1827",
                        "crew_serial_number": "2601",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "60",
                        "crew_profession_months": "3",
                        "crew_profession_days": "16",
                        "crew_profession_pension_funds": "3,89"
                    },
                    "19": {
                        "embarkation_port": "Marsiglia",
                        "embarkation_date": "1863-02-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1863-06-03",
                        "crew_surname": "Barbagelata",
                        "crew_name": "Michelangelo",
                        "crew_birth_location": "Sori",
                        "crew_birth_date": "1842",
                        "crew_serial_number": "11897",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "60",
                        "crew_profession_months": "3",
                        "crew_profession_days": "16",
                        "crew_profession_pension_funds": "3,89"
                    },
                    "20": {
                        "embarkation_port": "Marsiglia",
                        "embarkation_date": "1863-02-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1863-06-03",
                        "crew_surname": "Catterata",
                        "crew_name": "Andrea",
                        "crew_birth_location": "Sori",
                        "crew_birth_date": "1842",
                        "crew_serial_number": "14843",
                        "crew_profession_type": "Marinaio",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "60",
                        "crew_profession_months": "3",
                        "crew_profession_days": "16",
                        "crew_profession_pension_funds": "3,89"
                    },
                    "21": {
                        "embarkation_port": "Marsiglia",
                        "embarkation_date": "1863-02-18",
                        "discharge_port": "Genova",
                        "discharge_date": "1863-06-03",
                        "crew_surname": "Geriola",
                        "crew_name": "Nicolò Giovanni",
                        "crew_birth_location": "Sori",
                        "crew_birth_date": "1849",
                        "crew_serial_number": "19693",
                        "crew_profession_type": "Mozzo",
                        "crew_profession_wage": "Italian Lira",
                        "crew_profession_value": "12",
                        "crew_profession_months": "3",
                        "crew_profession_days": "16",
                        "crew_profession_pension_funds": "2,83"
                    },
                    "22": {},
                    "23": {},
                    "24": {},
                    "25": {}
                },
                "route": {
                    "0": {
                        "departure_port": "Genova",
                        "departure_date": "1862-02-16"
                    },
                    "1": {
                        "departure_port": "Costantinopoli",
                        "departure_date": "1862-03-31"
                    },
                    "2": {
                        "departure_port": "Kertch",
                        "departure_date": "1862-04-18"
                    },
                    "3": {
                        "departure_port": "Marianopoli",
                        "departure_date": "1862-05-03"
                    },
                    "4": {
                        "departure_port": "Costantinopoli",
                        "departure_date": "1862-05-14"
                    },
                    "5": {
                        "departure_port": "Cagliari",
                        "departure_date": "1862-06-05"
                    },
                    "6": {
                        "departure_port": "Genova",
                        "departure_date": "1862-07-07"
                    },
                    "7": {
                        "departure_port": "Costantinopoli",
                        "departure_date": "1862-08-15"
                    },
                    "8": {
                        "departure_port": "Kertch",
                        "departure_date": "1862-08-27"
                    },
                    "9": {
                        "departure_port": "Marianopoli",
                        "departure_date": "1862-09-12"
                    },
                    "10": {
                        "departure_port": "Costantinopoli",
                        "departure_date": "1862-09-22"
                    },
                    "11": {
                        "departure_port": "Livorno",
                        "departure_date": "1862-10-16"
                    },
                    "12": {
                        "arrival_port": "Marsiglia",
                        "arrival_date": "1862-10-25"
                    },
                    "13": {
                        "departure_port": "Marsiglia",
                        "departure_date": "1863-02-18"
                    },
                    "14": {
                        "departure_port": "Costantinopoli",
                        "departure_date": "1863-03-17"
                    },
                    "15": {
                        "departure_port": "Berdiansk",
                        "departure_date": "1863-04-27"
                    },
                    "16": {
                        "departure_port": "Costantinopoli",
                        "departure_date": "1863-05-06"
                    },
                    "17": {
                        "arrival_port": "Genova",
                        "arrival_date": "1863-06-03"
                    },
                    "18": {},
                    "19": {},
                    "20": {},
                    "21": {},
                    "22": {},
                    "23": {},
                    "24": {}
                }
            }
        }
    ]
}

]